server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true 
  output:
    ansi:
      enabled: always
  sql:
    init:
      schema-locations:
      data-locations:

  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  
mybatis:
  mapper-locations:
  - classpath:mapper/**.xml

